DROP DATABASE IF EXISTS auth;

CREAT DATABASE IF NOT EXISTS auth;

USE auth;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (50) NOT NULL,
    email VARCHAR(75) NOT NULL UNIQUE,
    password VARCHAR (200) NOT NULL
);
